model:
  base_learning_rate: 1.0e-06
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256  # Updated for f-16 configuration
    n_embed: 16384  # Increased for f-16 configuration
    ddconfig:
      double_z: True
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1, 1, 2, 2, 4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 1000
        disc_weight: 0.5
        codebook_weight: 1.0  # Adjusted for f-16 configuration

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4  # Increased for potential efficiency with f-16
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: text_training.txt
        size: 256
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: text_test.txt
        size: 256

lightning:
  trainer:
    max_epochs: 1000  # or set to -1 for unlimited training
    log_every_n_steps: 10
    accelerator: gpu
    devices: 1
    precision: 16  # Enable mixed-precision training
